export const images = {
  splash: require('../assets/images/ica.png'),
  ad1: require('../assets/advertisementImages/ad1.jpeg'),
  ad2: require('../assets/advertisementImages/ad2.png'),
  ad3: require('../assets/advertisementImages/ad3.jpeg'),
  ad4: require('../assets/advertisementImages/ad4.jpeg'),
  ad5: require('../assets/advertisementImages/ad5.jpeg'),
  ad7: require('../assets/advertisementImages/ad7.jpeg'),
  ad8: require('../assets/advertisementImages/ad8.png'),
  back: require('../assets/images/back.jpeg'),
  avatar: require('../assets/images/Avatar.png'),
  webdev: require('../assets/images/webdev.jpeg'),
  appdev: require('../assets/images/appdev.webp'),
  ethcking: require('../assets/images/ethcking.jpeg'),
  gamedev: require('../assets/images/gamedev.jpeg'),
  notify: require('../assets/images/notify.webp'),
};
